create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists clients_created_at_idx
  on public.clients (created_at desc);
